Repository DogSick/DogSick, pull requests merged in 2024-06, with the labels that each got.

#5 [FEATURE][DOCS][MODIFY] json file add
  json/서울시 강남구 동물병원 인허가 정보.json
Labels: 📃 Docs

#9 [FEATURE][MAP] map initial version
  .gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/mapMain.dart
  pubspec.yaml
Labels: 📬 API, ✨ Feature, ⚙ Setting

#11 [FEATURE][MAIN] 로딩메인, 메인 화면 구성, 페이지 연결
  .run/main.dart.run.xml
  assets/fonts/NotoSansKR-Black.otf
  assets/fonts/NotoSansKR-Bold.otf
  assets/fonts/NotoSansKR-Light.otf
  assets/fonts/NotoSansKR-Medium.otf
  assets/fonts/NotoSansKR-Regular.otf
  assets/fonts/NotoSansKR-Thin.otf
  assets/images/logo.jpg
  lib/firstScreen.dart
  lib/loadingMain.dart
  lib/main.dart
  pubspec.yaml
  test/widget_test.dart
Labels: ✨ Feature, 🎨 Html&css

#18 Feature/memo memo delete
  lib/main.dart
  lib/memo.dart
  lib/memoDetail.dart
  lib/newMemo.dart
  pubspec.yaml
  test/widget_test.dart
Labels: 📬 API, ✨ Feature, 🎨 Html&css, :pager: BackEnd

#21 [FEATURE][SEARCHHOSPITAL] 검색기능 및 리스트 추가
  assets/data/hospitalData.json
  json/서울시 강남구 동물병원 인허가 정보.json
  lib/main.dart
  lib/searchHospital.dart
  pubspec.yaml
Labels: ✨ Feature, :pager: BackEnd

#22 [FEATURE][EMERGENCY] EMERGENCY PAGE CALL (#16)
  android/app/src/main/AndroidManifest.xml
  lib/emergency.dart
  lib/main.dart
  pubspec.yaml
  test/widget_test.dart
Labels: ✨ Feature, 🎨 Html&css

#25 [FEATURE][SEARCHHOSPITAL] list css modify and detailButton add
  lib/searchHospital.dart
Labels: ✨ Feature, 🎨 Html&css

#28 [FEATURE][COMMON]location
  android/app/src/profile/AndroidManifest.xml
  android/settings.gradle
  lib/emergency.dart
  lib/firstScreen.dart
  lib/location.dart
  lib/mapMain.dart
  lib/memo.dart
  lib/memoDetail.dart
  lib/newMemo.dart
  lib/searchHospital.dart
  pubspec.yaml
Labels: 📬 API, ✨ Feature

#29 [FEATURE][MAP] 현재 위치와 가까운 병원 마킹
  android/app/src/main/AndroidManifest.xml
  assets/images/location_mark.png
  assets/images/marker.png
  lib/mapMain.dart
  pubspec.yaml
Labels: 📬 API, ✨ Feature

#31 [FEATURE][mainButton]메인 클릭 버튼 수정
  android/app/src/main/res/drawable-xxxhdpi/splash.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  assets/images/emergency.png
  assets/images/hospitalsearch.png
  assets/images/logo.jpg
  assets/images/myrecord.png
  assets/images/nearhospital.png
  lib/firstScreen.dart
  lib/loadingMain.dart
  lib/main.dart
Labels: ✨ Feature

#32 [FEATURE][SEARCHHOSPITAL] 뒤로가기 버튼 오류 수정
  lib/searchHospital.dart
Labels: 🐞 BugFix

#37 [FEATURE][EMERGENCY] EMERGENCY PAGE CALL (#35)
  assets/data/hospitalData.json
  lib/emergency.dart
  lib/firstScreen.dart
  lib/hospitalDetail.dart
  lib/location.dart
Labels: 📬 API, ✨ Feature, :pager: BackEnd

#40 [FEATURE][HOSPITALDETAIL] 동물병원 상세 페이지 뷰 및 기능 구현
  lib/hospitalDetail.dart
  lib/mapMain.dart
Labels: ✨ Feature, 🎨 Html&css

#43 [FEATURE][HOSPITALDETAIL] ERROR COMMIT
  android/app/src/main/AndroidManifest.xml
  lib/hospitalDetail.dart
Labels: ✨ Feature, 🔨 Refactor

#46 [FEATURE][DOCS][UPDATE] JSON IMAGE UPDATE
  assets/data/hospitalData.json
  lib/hospitalDetail.dart
Labels: 📃 Docs, 🎨 Html&css

#47 feature/mapBugFix 정보창 버그 수정 및 전화번호 텍스트 컬러 수정 (#44)
  lib/emergency.dart
  lib/hospitalDetail.dart
  lib/mapMain.dart
Labels: 🐞 BugFix, 🎨 Html&css
